"""empty message

Revision ID: a927fe4c9d09
Revises: 
Create Date: 2019-07-29 22:13:50.595564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a927fe4c9d09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
